Repository hsh-bis242/bis242base, pull requests merged in 2025-02, with the labels that each got.

#27 Fixes bug in source data
  willibald_dwh/seeds/psa_sl/roadshow_bestellung.csv
  willibald_dwh/seeds/psa_sl/webshop_kunde.csv
  willibald_dwh/seeds/psa_sl/webshop_lieferadresse.csv
  willibald_dwh/seeds/psa_sl/webshop_lieferung.csv
  willibald_dwh/seeds/psa_sl/webshop_position.csv
  willibald_dwh/seeds/psa_sl/webshop_produktkategorie.csv
  willibald_dwh/seeds/psa_sl/webshop_wohnort.csv
Labels: bug

#28 Ftr/21 reference tracking
  willibald_dwh/macros/dk_lsat.sql
  willibald_dwh/macros/link.sql
  willibald_dwh/macros/psa_view.sql
  willibald_dwh/models/psa_sl/v_webshop_produkt.sql
  willibald_dwh/models/rdv_il/_rdv_il__models.yml
  willibald_dwh/models/rdv_il/hub_productcategory.sql
  willibald_dwh/models/rdv_il/lnk_productcategory_supercategory.sql
  willibald_dwh/models/rdv_il/lsat_productcategory_supercategory_dkh.sql
  willibald_dwh/profiles.yml
  willibald_dwh/seeds/psa_sl/roadshow_bestellung.csv
  willibald_dwh/seeds/psa_sl/webshop_kunde.csv
  willibald_dwh/seeds/psa_sl/webshop_lieferadresse.csv
  willibald_dwh/seeds/psa_sl/webshop_lieferung.csv
  willibald_dwh/seeds/psa_sl/webshop_position.csv
  willibald_dwh/seeds/psa_sl/webshop_produktkategorie.csv
  willibald_dwh/seeds/psa_sl/webshop_wohnort.csv
Labels: enhancement

#31 Resolves #29
  willibald_dwh/README.md
  willibald_dwh/macros/dk_lsat.sql
Labels: bug

#32 Macro and metadata for reference tables
  willibald_dwh/macros/reftable.sql
  willibald_dwh/models/rdv_il/ref_deliveryevaluation.sql
  willibald_dwh/models/rdv_il/ref_producttype.sql
Labels: enhancement

#14 Ftr/3 link macro
  README.md
  willibald_dwh/README.md
  willibald_dwh/macros/dk_lsat.sql
  willibald_dwh/macros/hashcolumn.sql
  willibald_dwh/macros/hub.sql
  willibald_dwh/macros/link.sql
  willibald_dwh/macros/psa_view.sql
  willibald_dwh/macros/reftable.sql
  willibald_dwh/macros/sat.sql
  willibald_dwh/models/psa_sl/v_webshop_produkt.sql
  willibald_dwh/models/rdv_il/_rdv_il__models.yml
  willibald_dwh/models/rdv_il/hub_customer.sql
  willibald_dwh/models/rdv_il/hub_productcategory.sql
  willibald_dwh/models/rdv_il/lnk_customer_association.sql
  willibald_dwh/models/rdv_il/lnk_customer_residence.sql
  willibald_dwh/models/rdv_il/lnk_productcategory_supercategory.sql
  willibald_dwh/models/rdv_il/lsat_productcategory_supercategory_dkh.sql
  willibald_dwh/models/rdv_il/ref_deliveryevaluation.sql
  willibald_dwh/models/rdv_il/ref_producttype.sql
  willibald_dwh/models/rdv_il/sat_customer_context.sql
  willibald_dwh/profiles.yml
  willibald_dwh/seeds/psa_sl/_psa_sl__seeds.yml
  willibald_dwh/seeds/psa_sl/roadshow_bestellung.csv
  willibald_dwh/seeds/psa_sl/webshop_kunde.csv
  willibald_dwh/seeds/psa_sl/webshop_lieferadresse.csv
  willibald_dwh/seeds/psa_sl/webshop_lieferung.csv
  willibald_dwh/seeds/psa_sl/webshop_position.csv
  willibald_dwh/seeds/psa_sl/webshop_produktkategorie.csv
  willibald_dwh/seeds/psa_sl/webshop_wohnort.csv
Labels: bug, enhancement

#35 Made some fixes to the hubs to make dbt build again
  willibald_dwh/models/rdv_il/hub_deliveryaddress.sql
  willibald_dwh/models/rdv_il/hub_product.sql
  willibald_dwh/models/rdv_il/hub_roadshowsale.sql
  willibald_dwh/models/rdv_il/lnk_roadshowsale.sql
Labels: bug

#38 Some fixes on the links, to make dbt build again
  willibald_dwh/models/rdv_il/_rdv_il__models.yml
  willibald_dwh/models/rdv_il/lnk_productcategory_supercategory.sql
  willibald_dwh/models/rdv_il/lnk_webshoporder_deliveryaddress.sql
  willibald_dwh/models/rdv_il/lnk_webshoporder_webshoporderitem.sql
  willibald_dwh/models/rdv_il/lnk_webshoporderitem_delivery.sql
  willibald_dwh/models/rdv_il/lnk_webshoporderitem_deliveryaddress.sql
Labels: bug

#41 Fixes the definition of the lsats
  willibald_dwh/models/rdv_il/lsat_customer_residence_context.sql
  willibald_dwh/models/rdv_il/lsat_roadshowsale_context.sql
Labels: bug

#42 Adds some tests for sats. Fixes some minor bugs in the sats
  willibald_dwh/models/rdv_il/_rdv_il__models.yml
  willibald_dwh/models/rdv_il/sat_association_context.sql
  willibald_dwh/models/rdv_il/sat_webshoporder_context.sql
  willibald_dwh/models/rdv_il/sat_webshoporderitem_context.sql
Labels: bug

#46 added the first dk lsat
  willibald_dwh/models/rdv_il/lsat_association_customer_dkh.sql
  willibald_dwh/models/rdv_il/lsat_customer_association_dkh.sql
  willibald_dwh/models/rdv_il/lsat_customer_creditcard_dkh.sql
  willibald_dwh/models/rdv_il/lsat_product_productcategorydkh.sql
  willibald_dwh/models/rdv_il/lsat_webshoporder_customer_dkh.sql
  willibald_dwh/models/rdv_il/lsat_webshoporder_deliveryaddress_dkh.sql
  willibald_dwh/models/rdv_il/lsat_webshoporder_webshoporderitem_dkh.sql
  willibald_dwh/models/rdv_il/lsat_webshoporderitem_delivery_dkh.sql
  willibald_dwh/models/rdv_il/lsat_webshoporderitem_deliveryaddress_dkh.sql
  willibald_dwh/models/rdv_il/lsat_webshoporderitem_product_dkh.sql
Labels: enhancement
